# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170820_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnAvailableTimes',
            new_name='AvailableTimes',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Building'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='notification date'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Building'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestletter',
            name='text',
            field=models.TextField(),
        ),
    ]
