# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_requestletter_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestletter',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 17, 46, 24, 371943), verbose_name='notification date'),
        ),
    ]
