# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20170824_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=20, primary_key=True),
        ),
        migrations.AlterField(
            model_name='requestletter',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 19, 19, 21, 179974), verbose_name='notification date'),
        ),
    ]
