# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20170824_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestletter',
            name='date_time',
        ),
    ]
