# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_remove_requestletter_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=20, primary_key=True),
        ),
    ]
