# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_facility_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Bill')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Charge')),
                ('receiving_neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor')),
            ],
        ),
    ]
