# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_warning'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='_apartment',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='_owner',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='_apartment',
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='_bank',
        ),
        migrations.DeleteModel(
            name='Salam',
        ),
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='receipt',
        ),
        migrations.AddField(
            model_name='bill',
            name='payed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='payed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='payed_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
        ),
        migrations.AddField(
            model_name='warningletter',
            name='title',
            field=models.CharField(default='bad neighbor', max_length=300),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
        ),
        migrations.AlterField(
            model_name='warningletter',
            name='text',
            field=models.CharField(max_length=30000),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayment',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='warningletter',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='warningletter',
            name='number',
        ),
        migrations.RemoveField(
            model_name='warningletter',
            name='receiving_neighbor',
        ),
    ]
