# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20170826_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletimes',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
